repos:
  - repo: local
    hooks:
      - id: make-lint-check
        name: Lint with Makefile
        entry: make lint-check
        language: system
        types: [python]
        pass_filenames: false
