"""Tests for the video prompt generation feature."""

import os
from unittest.mock import MagicMock, patch

from storyforge.llm_backend import LLMBackend

# ---------------------------------------------------------------------------
# DummyBackend for testing base class helpers
# ---------------------------------------------------------------------------


class DummyVideoBackend(LLMBackend):
    """Minimal concrete implementation for testing base class video methods."""

    name = "dummy_video"

    def generate_story(self, prompt):
        raise NotImplementedError

    def generate_image(self, prompt, reference_image_bytes=None, override_prompt=None):
        raise NotImplementedError

    def generate_image_name(self, prompt, story):
        raise NotImplementedError

    def generate_image_prompt(self, story, context, num_prompts):
        raise NotImplementedError

    def generate_video_prompt(self, story, context, num_scenes):
        raise NotImplementedError


# ---------------------------------------------------------------------------
# _build_video_prompt_request tests
# ---------------------------------------------------------------------------


class TestBuildVideoPromptRequest:
    """Test _build_video_prompt_request helper."""

    def test_basic_video_prompt_request(self):
        backend = DummyVideoBackend()
        result = backend._build_video_prompt_request("A test story.", "", 3)
        assert "3" in result
        assert "video" in result.lower()
        assert "A test story" in result
        assert "Camera" in result
        assert "Lighting" in result
        assert "Action" in result

    def test_video_prompt_includes_context(self):
        backend = DummyVideoBackend()
        result = backend._build_video_prompt_request("Story.", "Forest at night", 2)
        assert "Forest at night" in result
        assert "CONTEXT" in result

    def test_video_prompt_includes_character_descriptions(self):
        backend = DummyVideoBackend()
        result = backend._build_video_prompt_request(
            "Story.", "", 2, character_descriptions="Luna: golden hair, blue dress"
        )
        assert "Luna: golden hair, blue dress" in result
        assert "CHARACTER VISUAL DESCRIPTIONS" in result

    def test_video_prompt_scene_count(self):
        backend = DummyVideoBackend()
        result = backend._build_video_prompt_request("Story.", "", 5)
        assert "Scene 1:" in result
        assert "Scene 5:" in result


# ---------------------------------------------------------------------------
# _generate_fallback_video_prompts tests
# ---------------------------------------------------------------------------


class TestFallbackVideoPrompts:
    """Test _generate_fallback_video_prompts fallback method."""

    def test_fallback_returns_correct_count(self):
        backend = DummyVideoBackend()
        result = backend._generate_fallback_video_prompts("A story.\nPart two.\nPart three.", "", 3)
        assert len(result) == 3

    def test_fallback_includes_cinematic_language(self):
        backend = DummyVideoBackend()
        result = backend._generate_fallback_video_prompts("A story.", "", 1)
        assert "cinematic" in result[0].lower()

    def test_fallback_includes_context(self):
        backend = DummyVideoBackend()
        result = backend._generate_fallback_video_prompts("A story.", "Enchanted forest", 1)
        assert "Enchanted forest" in result[0]

    def test_fallback_includes_story_segments(self):
        backend = DummyVideoBackend()
        story = "The journey begins.\nThe conflict rises.\nThe hero triumphs."
        result = backend._generate_fallback_video_prompts(story, "", 3)
        assert "journey begins" in result[0]
        assert "hero triumphs" in result[2]


# ---------------------------------------------------------------------------
# format_video_prompt_file tests
# ---------------------------------------------------------------------------


class TestFormatVideoPromptFile:
    """Test format_video_prompt_file static method."""

    def test_format_with_story_prompt(self):
        prompts = ["Scene one description.", "Scene two description."]
        result = LLMBackend.format_video_prompt_file(prompts, "A brave cat")
        assert "Video Prompt — A brave cat" in result
        assert "Generated by StoryForge" in result
        assert "SCENE 1:" in result
        assert "SCENE 2:" in result
        assert "Scene one description." in result
        assert "Scene two description." in result

    def test_format_without_story_prompt(self):
        prompts = ["Only scene."]
        result = LLMBackend.format_video_prompt_file(prompts)
        assert result.startswith("Video Prompt\n")
        assert "SCENE 1:" in result

    def test_format_scene_labels(self):
        prompts = ["A", "B", "C"]
        result = LLMBackend.format_video_prompt_file(prompts)
        assert "Opening" in result
        assert "Climactic" in result or "closing" in result.lower()


# ---------------------------------------------------------------------------
# Backend generate_video_prompt tests (Gemini)
# ---------------------------------------------------------------------------


class TestGeminiVideoPrompt:
    """Test GeminiBackend.generate_video_prompt."""

    @patch.dict(os.environ, {"GEMINI_API_KEY": "test_key"})
    @patch("storyforge.gemini_backend.genai.Client")
    def test_generate_video_prompt_success(self, mock_client_class):
        from storyforge.gemini_backend import GeminiBackend

        mock_client = MagicMock()
        mock_client_class.return_value = mock_client

        mock_response = MagicMock()
        mock_response.text = "1. A cinematic opening scene.\n2. An action-packed middle.\n3. A closing shot."
        mock_client.models.generate_content.return_value = mock_response

        backend = GeminiBackend()
        result = backend.generate_video_prompt("A test story.", "", 3)

        assert len(result) == 3
        assert "cinematic opening" in result[0].lower()
        mock_client.models.generate_content.assert_called_once()

    @patch.dict(os.environ, {"GEMINI_API_KEY": "test_key"})
    @patch("storyforge.gemini_backend.genai.Client")
    def test_generate_video_prompt_fallback_on_error(self, mock_client_class):
        from storyforge.gemini_backend import GeminiBackend

        mock_client = MagicMock()
        mock_client_class.return_value = mock_client
        mock_client.models.generate_content.side_effect = Exception("API error")

        backend = GeminiBackend()
        result = backend.generate_video_prompt("A story.", "", 2)

        assert len(result) == 2
        assert "cinematic" in result[0].lower()


# ---------------------------------------------------------------------------
# Backend generate_video_prompt tests (OpenAI)
# ---------------------------------------------------------------------------


class TestOpenAIVideoPrompt:
    """Test OpenAIBackend.generate_video_prompt."""

    @patch.dict(os.environ, {"OPENAI_API_KEY": "test_key"})
    @patch("storyforge.openai_backend.openai.OpenAI")
    def test_generate_video_prompt_success(self, mock_openai_class):
        from storyforge.openai_backend import OpenAIBackend

        mock_client = MagicMock()
        mock_openai_class.return_value = mock_client

        mock_response = MagicMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "1. Opening scene.\n2. Closing scene."
        mock_response.choices = [mock_choice]
        mock_client.chat.completions.create.return_value = mock_response

        backend = OpenAIBackend()
        result = backend.generate_video_prompt("A test story.", "", 2)

        assert len(result) == 2

    @patch.dict(os.environ, {"OPENAI_API_KEY": "test_key"})
    @patch("storyforge.openai_backend.openai.OpenAI")
    def test_generate_video_prompt_fallback_on_error(self, mock_openai_class):
        from storyforge.openai_backend import OpenAIBackend

        mock_client = MagicMock()
        mock_openai_class.return_value = mock_client
        mock_client.chat.completions.create.side_effect = Exception("API error")

        backend = OpenAIBackend()
        result = backend.generate_video_prompt("A story.", "", 2)

        assert len(result) == 2


# ---------------------------------------------------------------------------
# Backend generate_video_prompt tests (Anthropic)
# ---------------------------------------------------------------------------


class TestAnthropicVideoPrompt:
    """Test AnthropicBackend.generate_video_prompt."""

    @patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test_key"})
    @patch("storyforge.anthropic_backend.anthropic.Anthropic")
    def test_generate_video_prompt_success(self, mock_anthropic_class):
        from storyforge.anthropic_backend import AnthropicBackend

        mock_client = MagicMock()
        mock_anthropic_class.return_value = mock_client

        mock_response = MagicMock()
        mock_block = MagicMock()
        mock_block.text = "1. Opening scene.\n2. Middle scene.\n3. Closing scene."
        mock_response.content = [mock_block]
        mock_client.messages.create.return_value = mock_response

        backend = AnthropicBackend()
        result = backend.generate_video_prompt("A test story.", "", 3)

        assert len(result) == 3

    @patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test_key"})
    @patch("storyforge.anthropic_backend.anthropic.Anthropic")
    def test_generate_video_prompt_fallback_on_error(self, mock_anthropic_class):
        from storyforge.anthropic_backend import AnthropicBackend

        mock_client = MagicMock()
        mock_anthropic_class.return_value = mock_client
        mock_client.messages.create.side_effect = Exception("API error")

        backend = AnthropicBackend()
        result = backend.generate_video_prompt("A story.", "", 2)

        assert len(result) == 2
